### PR TITLE
Updating packages to eliminate security violations.

### PR DESCRIPTION
**Pull request by ereddrex**
# Summary

This package uses an older version of css-select that is dependent upon a css-what package that contains high priority security violations. I am updating dependencies of this package newer, non-violating packages.

## Test Plan

Ran existing tests and all were successful.

### CODE REVIEW

**Comment by ereddrex** [comment]
#1598 requires the package update contained in this package, among others.

**Comment by ereddrex** [comment]
@magicismight, could this PR be prioritized for review and commit?

**Comment by brentvatne** [comment]
https://overreacted.io/npm-audit-broken-by-design/

**Comment by gbhasha** [comment]
@ereddrex - please resolve the conflict. v12.2.0 is already released, you may need to make change in package.json and increment the version number

**Comment by ereddrex** [comment]
I waited months for this PR to get reviewed and got assigned to different work-efforts and haven't had time, months later, to return to this. 

Looks like Jyrno42 has taken up the mantle and has further updated this work. Closing this as a duplicate.

**Pull request closed without merging**
