### PR TITLE
Update to css-select to avoid security warnings

### PR DESCRIPTION
**Pull request by ericanderson**
# Summary

nth-check has a security vulnerability and is depended on by css-select. Updates css-select to fix.

### CODE REVIEW

**Review by MadeinFrance — APPROVED** [review]

**Comment by jphpsf** [comment]
Thank you for the PR @ericanderson! Looking forward to see this in a release soon :)

**Review by WoLewicki — APPROVED** [review]
LGTM!

**Comment by yoelianto** [comment]
Error css-select

error: Error: Unable to resolve module ./procedure.json from /home/antok/Projects/react-native/Newstensity/node_modules/css-select/lib/compile.js: 

None of these files exist:
  * node_modules/css-select/lib/procedure.json(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * node_modules/css-select/lib/procedure.json/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
> 1 | "use strict";
  2 | var __importDefault = (this && this.__importDefault) || function (mod) {
  3 |     return (mod && mod.__esModule) ? mod : { "default": mod };
  4 | };

**Comment by yoelianto** [comment]
Errot css-select

I think the filename not procedure.json but procedure.js

error: Error: Unable to resolve module ./procedure.json from /home/******/css-select/lib/compile.js: 

None of these files exist:
  * node_modules/css-select/lib/procedure.json(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * node_modules/css-select/lib/procedure.json/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
> 1 | "use strict";
  2 | var __importDefault = (this && this.__importDefault) || function (mod) {
  3 |     return (mod && mod.__esModule) ? mod : { "default": mod };
  4 | };

**Pull request merged**
