### PR TITLE
Adding mavenCentral() as jcenter() is shutting

### PR DESCRIPTION
**Pull request by maheshwarimrinal**
Adding mavenCentral() as jcenter() is shutting down

### CODE REVIEW

**Comment by pvegh** [comment]
We'd like to see this released ASAP for obvious reasons :)

**Comment by pvegh** [comment]
Ping :)

**Comment by pvegh** [comment]
Can this be merged?

**Comment by maheshwarimrinal** [comment]
@pvegh create a patch for this at least you can continue your work

**Comment by pvegh** [comment]
I'm not blocked but I'd like to see these fixes in all upstream libs we're using, so we can switch ASAP without any workarounds. Currently it's a good show case why NOT to use RN :)

**Comment by mkarkachov** [comment]
@brentvatne can you approve this one pls?

**Comment by pvegh** [comment]
This is getting critical, it's now 2022 ans JCenter showdown is very soon

**Review by WoLewicki — APPROVED** [review]
Thanks for this change :tada:

**Comment by larsmunkholm** [comment]
Will npm package be updated soon? Last publish was 6 months ago.

**Comment by WoLewicki** [comment]
We are planning on doing it soon.

**Pull request merged**
