### PR TITLE
Xcode 12 use_frameworks compatibility

### PR DESCRIPTION
**Pull request by chrmod**
Reference https://github.com/facebook/react-native/issues/29633#issuecomment-694187116

# Summary

Explain the **motivation** for making this change: here are some points to help you:

* What issues does the pull request solve? Please tag them so that they will get automatically closed once the PR is merged
* What is the feature? (if applicable)
* How did you implement the solution?
* What areas of the library does it impact?

## Test Plan

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added documentation in `README.md`
- [ ] I updated the typed files (typescript)
- [ ] I added a test for the API in the `__tests__` folder

### CODE REVIEW

**Review by karvulf — APPROVED** [review]

**Review by karvulf — CHANGES_REQUESTED** [review]
Package cannot be installed

**Comment by Gethyl** [comment]
Sorry, didn't see that there was a PR already for this. I created an issue for the same. Should I close it? https://github.com/react-native-svg/react-native-svg/issues/1510

**Comment by Gethyl** [comment]
@karvulf may I didn't get your comment, is there an issue when you try to install? I made the change locally in my machine and it works as expected.

Screen Shot 2020-12-18 at 12 14 15 pm

and after pod install, **React.framework** is linked.

Screen Shot 2020-12-18 at 12 15 11 pm

**Comment by The0racle** [comment]
When will this be merged?

**Comment by WoLewicki** [comment]
Since https://github.com/react-native-svg/react-native-svg/pull/1604 has been merged, I will close it. Feel free to comment here if something is wrong and we can always reopen it. Thanks for your contribution :tada:

**Pull request closed without merging**
