### PR TITLE
[feature] add onLoad to SvgUri and fix typings for LocalSvg

### PR DESCRIPTION
**Pull request by harveyconnor**
# Summary

- Added a simple onLoad prop to the SvgUri
  - Allows users to show a loading state in their implementation whilst fetching the svg from the server.
- Added typings for LocalSvg class in the index.d.ts
  - Resolves issues when trying to import LocalSvg via TypeScript

## Test Plan

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

### What's required for testing (prerequisites)?
Nothing, everything should work as is.

### What are the steps to reproduce (after prerequisites)?
Import the LocalSvg using TypeScript or apply a onLoad attribute prop to the SvgUri.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added documentation in `README.md`
- [x] I updated the typed files (typescript)
- [x] I added a test for the API in the `__tests__` folder

### CODE REVIEW

**Comment by huming2207** [comment]
lgtm

**Comment by dannyifang** [comment]
lgtm

**Comment by harveyconnor** [comment]
Can we get this merged please? @msand

**Comment by huming2207** [comment]
> Can we get this merged please? @msand 

gg

**Comment by harveyconnor** [comment]
can we get this merged?

**Comment by nickmcmillan** [comment]
Still no merge? Seems like it's good to go.

**Comment by harveyconnor** [comment]
dead repo

**Comment by ayu-webmaster** [comment]
@magicismight

**Comment by lucascorrea97** [comment]
Can we please merge this??

**Comment by harveyconnor** [comment]
repo is dead so create your own or patch-package

**Review by catarinamateus — APPROVED** [review]

**Comment by WoLewicki** [comment]
@harveyconnor could you rebase to the newest `develop` branch, remove the changes not concerning this PR, and add a test example to `TestsExample` project where we could test this change? It would greatly shorten the time the maintainers would need to spend in order to get this merged. Thank you in advance 🙏

**Comment by harveyconnor** [comment]
> @harveyconnor could you rebase to the newest `develop` branch, remove the changes not concerning this PR, and add a test example to `TestsExample` project where we could test this change? It would greatly shorten the time the maintainers would need to spend in order to get this merged. Thank you in advance 🙏

I made this PR a very long time ago...

**Comment by WoLewicki** [comment]
Yeah, I see 😅  Will you be able to do that or should someone make a new one with those changes?

**Comment by harveyconnor** [comment]
I currently don't have time to do that unfortunately.

**Comment by WoLewicki** [comment]
Since #1817 has been merged, I will close this PR. Thanks for your contribution!

**Pull request closed without merging**
