### PR TITLE
fix(jcenter): remove jcenter

### PR DESCRIPTION
**Pull request by Bibazavr**
# Summary

Builds will no longer be able to resolve artifacts from JCenter after February 1st, 2022 because jcenter servers shut down

so, I remove jcenter and update react-native (since 0.65.1 they don't use jcenter)

## Test Plan

Just try run apps with this changes  

### What's required for testing (prerequisites)?

nothing

### What are the steps to reproduce (after prerequisites)?

Just try run apps with this changes  

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
~~- [ ] I added documentation in `README.md`~~
~~- [ ] I updated the typed files (typescript)~~
~~- [ ] I added a test for the API in the `__tests__` folder~~

Refs: https://github.com/react-native-svg/react-native-svg/pull/1570, #1573

### CODE REVIEW

**Comment by Udbhav12** [comment]
When is this getting merged ?

**Comment by matteodanelli** [comment]
News or updates? It seems fine and ready for merge.

**Review by ignacioazo — APPROVED** [review]

**Comment by aleksamrakovic** [comment]
Do we have any updates here? Jcenter is shutting down in few days

**Comment by matteodanelli** [comment]
@aleksamrakovic  Luckily, jcenter will be read-only indefinitely.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by larsmunkholm** [comment]
Doesnt really matter that it's read-only if you get a gateway error once a week or more.

**Comment by aleksamrakovic** [comment]
Yes, it would be nice to know whether should we expect an update or focus on alternatives

**Review by BogdanRad — APPROVED** [review]

**Comment by WoLewicki** [comment]
Since https://github.com/react-native-svg/react-native-svg/pull/1570 has been merged, I will close this PR as it trying to do the same thing. Feel free to comment here if I am wrong and we can reopen it then.

**Pull request closed without merging**
